-- AromaLParfum — PASO 58 — Reseñas Verificadas V2
-- Ejecutar UNA sola vez en Supabase > SQL Editor.
-- Objetivos:
-- 1) aceptar reseñas únicamente de pedidos ENTREGADOS y productos realmente comprados;
-- 2) moderarlas antes de publicarlas;
-- 3) no exponer email, teléfono, dirección, order_id ni datos internos al público;
-- 4) cargar reseñas bajo demanda desde la ficha del producto.

begin;

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  order_item_id bigint references public.order_items(id) on delete set null,
  purchase_type text not null default 'product',
  reviewer_display_name text not null default 'Cliente verificado',
  rating smallint not null,
  title text,
  body text not null,
  verified_purchase boolean not null default true,
  status text not null default 'pending',
  featured boolean not null default false,
  admin_note text,
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  moderated_by text,
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint product_reviews_rating_check check (rating between 1 and 5),
  constraint product_reviews_status_check check (status in ('pending','approved','rejected')),
  constraint product_reviews_order_product_unique unique (order_id, product_id)
);

-- Compatibilidad si la tabla ya existiera de una prueba anterior.
alter table public.product_reviews add column if not exists order_item_id bigint references public.order_items(id) on delete set null;
alter table public.product_reviews add column if not exists purchase_type text not null default 'product';
alter table public.product_reviews add column if not exists reviewer_display_name text not null default 'Cliente verificado';
alter table public.product_reviews add column if not exists verified_purchase boolean not null default true;
alter table public.product_reviews add column if not exists status text not null default 'pending';
alter table public.product_reviews add column if not exists featured boolean not null default false;
alter table public.product_reviews add column if not exists admin_note text;
alter table public.product_reviews add column if not exists moderated_at timestamptz;
alter table public.product_reviews add column if not exists moderated_by text;
alter table public.product_reviews add column if not exists published_at timestamptz;
alter table public.product_reviews add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'product_reviews_order_product_unique'
      and conrelid = 'public.product_reviews'::regclass
  ) then
    alter table public.product_reviews
      add constraint product_reviews_order_product_unique unique (order_id, product_id);
  end if;
end;
$$;

create index if not exists product_reviews_public_idx
  on public.product_reviews (product_id, status, featured desc, published_at desc, created_at desc);

create index if not exists product_reviews_admin_idx
  on public.product_reviews (status, created_at desc);

alter table public.product_reviews enable row level security;

-- Nadie desde el navegador lee o modifica la tabla directamente.
revoke all on table public.product_reviews from anon, authenticated;

-- ---------- PUBLICO: leer únicamente reseñas aprobadas ----------
create or replace function public.get_product_reviews_v2(
  p_product_id bigint,
  p_limit integer default 8,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint := p_product_id;
  v_limit integer := greatest(1, least(coalesce(p_limit, 8), 20));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
  v_total integer := 0;
  v_average numeric := 0;
  v_ratings jsonb := '{}'::jsonb;
  v_rows jsonb := '[]'::jsonb;
begin
  if v_product_id is null or v_product_id <= 0 then
    return jsonb_build_object('ok', false, 'error', 'invalid_product');
  end if;

  select
    count(*)::integer,
    coalesce(round(avg(r.rating)::numeric, 2), 0)
  into v_total, v_average
  from public.product_reviews r
  where r.product_id = v_product_id
    and r.status = 'approved';

  select jsonb_build_object(
    '5', count(*) filter (where rating = 5),
    '4', count(*) filter (where rating = 4),
    '3', count(*) filter (where rating = 3),
    '2', count(*) filter (where rating = 2),
    '1', count(*) filter (where rating = 1)
  )
  into v_ratings
  from public.product_reviews
  where product_id = v_product_id
    and status = 'approved';

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', x.id,
        'display_name', x.reviewer_display_name,
        'rating', x.rating,
        'title', x.title,
        'body', x.body,
        'verified_purchase', x.verified_purchase,
        'purchase_type', x.purchase_type,
        'featured', x.featured,
        'created_at', x.created_at
      )
      order by x.featured desc, x.published_at desc nulls last, x.created_at desc
    ),
    '[]'::jsonb
  )
  into v_rows
  from (
    select
      r.id,
      r.reviewer_display_name,
      r.rating,
      r.title,
      r.body,
      r.verified_purchase,
      r.purchase_type,
      r.featured,
      r.created_at,
      r.published_at
    from public.product_reviews r
    where r.product_id = v_product_id
      and r.status = 'approved'
    order by r.featured desc, r.published_at desc nulls last, r.created_at desc
    limit v_limit
    offset v_offset
  ) x;

  return jsonb_build_object(
    'ok', true,
    'product_id', v_product_id,
    'summary', jsonb_build_object(
      'average_rating', v_average,
      'review_count', v_total,
      'ratings', coalesce(v_ratings, '{}'::jsonb)
    ),
    'reviews', v_rows,
    'limit', v_limit,
    'offset', v_offset
  );
end;
$$;

-- ---------- PUBLICO: enviar una reseña verificada ----------
create or replace function public.submit_verified_product_review_v2(
  p_product_id bigint,
  p_order_code text,
  p_contact text,
  p_rating integer,
  p_title text default null,
  p_body text default null,
  p_display_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_item record;
  v_review_id bigint;
  v_code text := upper(trim(coalesce(p_order_code, '')));
  v_contact text := trim(coalesce(p_contact, ''));
  v_contact_digits text := regexp_replace(coalesce(p_contact, ''), '[^0-9]', '', 'g');
  v_title text := nullif(trim(coalesce(p_title, '')), '');
  v_body text := trim(coalesce(p_body, ''));
  v_name text := trim(coalesce(p_display_name, ''));
begin
  if p_product_id is null or p_product_id <= 0 then
    return jsonb_build_object('ok', false, 'error', 'invalid_product');
  end if;

  if v_code = '' or v_contact = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_order_identity');
  end if;

  if p_rating is null or p_rating < 1 or p_rating > 5 then
    return jsonb_build_object('ok', false, 'error', 'invalid_rating');
  end if;

  if length(v_body) < 10 then
    return jsonb_build_object('ok', false, 'error', 'review_too_short');
  end if;

  if length(v_body) > 1200 then
    return jsonb_build_object('ok', false, 'error', 'review_too_long');
  end if;

  if v_title is not null and length(v_title) > 90 then
    return jsonb_build_object('ok', false, 'error', 'title_too_long');
  end if;

  if v_name = '' then
    v_name := 'Cliente verificado';
  end if;

  if length(v_name) > 40 then
    v_name := left(v_name, 40);
  end if;

  select o.id, o.status, o.order_code
  into v_order
  from public.orders o
  where upper(trim(coalesce(o.order_code, ''))) = v_code
    and (
      lower(trim(coalesce(o.customer_email, ''))) = lower(v_contact)
      or (
        length(v_contact_digits) >= 6
        and regexp_replace(coalesce(o.customer_phone, ''), '[^0-9]', '', 'g') = v_contact_digits
      )
    )
  order by o.id desc
  limit 1;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'order_not_found');
  end if;

  if lower(coalesce(v_order.status, '')) <> 'entregado' then
    return jsonb_build_object('ok', false, 'error', 'order_not_delivered');
  end if;

  select oi.id, coalesce(oi.item_type, 'product') as item_type
  into v_item
  from public.order_items oi
  where oi.order_id = v_order.id
    and oi.product_id = p_product_id
  order by oi.id
  limit 1;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'product_not_in_order');
  end if;

  if exists (
    select 1
    from public.product_reviews pr
    where pr.order_id = v_order.id
      and pr.product_id = p_product_id
  ) then
    return jsonb_build_object('ok', false, 'error', 'already_reviewed');
  end if;

  insert into public.product_reviews (
    product_id,
    order_id,
    order_item_id,
    purchase_type,
    reviewer_display_name,
    rating,
    title,
    body,
    verified_purchase,
    status,
    featured
  )
  values (
    p_product_id,
    v_order.id,
    v_item.id,
    v_item.item_type,
    v_name,
    p_rating,
    v_title,
    v_body,
    true,
    'pending',
    false
  )
  returning id into v_review_id;

  return jsonb_build_object(
    'ok', true,
    'review_id', v_review_id,
    'status', 'pending',
    'verified_purchase', true
  );
end;
$$;

-- ---------- ADMIN: listado y métricas ----------
create or replace function public.admin_get_product_reviews_v2(
  p_status text default 'pending',
  p_search text default '',
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_status text := lower(trim(coalesce(p_status, 'pending')));
  v_search text := trim(coalesce(p_search, ''));
  v_limit integer := greatest(1, least(coalesce(p_limit, 20), 50));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
  v_total integer := 0;
  v_rows jsonb := '[]'::jsonb;
  v_stats jsonb := '{}'::jsonb;
begin
  if v_email <> 'defanissantiago@gmail.com' then
    raise exception 'Solo administrador.';
  end if;

  if v_status not in ('all','pending','approved','rejected') then
    v_status := 'pending';
  end if;

  select jsonb_build_object(
    'pending', count(*) filter (where r.status = 'pending'),
    'approved', count(*) filter (where r.status = 'approved'),
    'rejected', count(*) filter (where r.status = 'rejected'),
    'featured', count(*) filter (where r.featured = true and r.status = 'approved'),
    'approved_average', coalesce(round((avg(r.rating) filter (where r.status = 'approved'))::numeric, 2), 0)
  )
  into v_stats
  from public.product_reviews r;

  select count(*)::integer
  into v_total
  from public.product_reviews r
  join public.products p on p.id = r.product_id
  where (v_status = 'all' or r.status = v_status)
    and (
      v_search = ''
      or p.nombre ilike '%' || v_search || '%'
      or r.reviewer_display_name ilike '%' || v_search || '%'
      or coalesce(r.title, '') ilike '%' || v_search || '%'
      or r.body ilike '%' || v_search || '%'
    );

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb)
  into v_rows
  from (
    select
      r.id,
      r.product_id,
      p.nombre as product_name,
      r.reviewer_display_name as display_name,
      r.rating,
      r.title,
      r.body,
      r.purchase_type,
      r.verified_purchase,
      r.status,
      r.featured,
      r.admin_note,
      r.created_at,
      r.moderated_at,
      r.published_at,
      o.order_code
    from public.product_reviews r
    join public.products p on p.id = r.product_id
    join public.orders o on o.id = r.order_id
    where (v_status = 'all' or r.status = v_status)
      and (
        v_search = ''
        or p.nombre ilike '%' || v_search || '%'
        or r.reviewer_display_name ilike '%' || v_search || '%'
        or coalesce(r.title, '') ilike '%' || v_search || '%'
        or r.body ilike '%' || v_search || '%'
      )
    order by r.created_at desc
    limit v_limit
    offset v_offset
  ) x;

  return jsonb_build_object(
    'ok', true,
    'total', v_total,
    'stats', v_stats,
    'rows', v_rows,
    'limit', v_limit,
    'offset', v_offset
  );
end;
$$;

-- ---------- ADMIN: moderar / destacar ----------
create or replace function public.admin_update_product_review_v2(
  p_review_id bigint,
  p_status text default null,
  p_featured boolean default null,
  p_admin_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_status text := case when p_status is null then null else lower(trim(p_status)) end;
  v_row record;
begin
  if v_email <> 'defanissantiago@gmail.com' then
    raise exception 'Solo administrador.';
  end if;

  if p_review_id is null or p_review_id <= 0 then
    return jsonb_build_object('ok', false, 'error', 'invalid_review');
  end if;

  if v_status is not null and v_status not in ('pending','approved','rejected') then
    return jsonb_build_object('ok', false, 'error', 'invalid_status');
  end if;

  update public.product_reviews r
  set
    status = coalesce(v_status, r.status),
    featured = case
      when coalesce(v_status, r.status) <> 'approved' then false
      when p_featured is null then r.featured
      else p_featured
    end,
    admin_note = case when p_admin_note is null then r.admin_note else nullif(trim(p_admin_note), '') end,
    moderated_at = case when v_status is not null then now() else r.moderated_at end,
    moderated_by = case when v_status is not null then v_email else r.moderated_by end,
    published_at = case
      when v_status = 'approved' and r.published_at is null then now()
      when v_status in ('pending','rejected') then null
      else r.published_at
    end,
    updated_at = now()
  where r.id = p_review_id
  returning r.id, r.status, r.featured into v_row;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;

  return jsonb_build_object(
    'ok', true,
    'id', v_row.id,
    'status', v_row.status,
    'featured', v_row.featured
  );
end;
$$;

-- ---------- PASO 57 mejorado: seguimiento puede ofrecer reseña ----------
-- Mantiene la misma firma y sigue sin exponer identidad/dirección.
create or replace function public.get_public_order_status(
  p_order_code text,
  p_contact text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_items jsonb := '[]'::jsonb;
  v_code text := upper(trim(coalesce(p_order_code, '')));
  v_contact text := trim(coalesce(p_contact, ''));
  v_contact_digits text := regexp_replace(coalesce(p_contact, ''), '[^0-9]', '', 'g');
begin
  if v_code = '' or v_contact = '' then
    return jsonb_build_object('ok', false, 'error', 'missing_fields');
  end if;

  select
    o.id,
    o.order_code,
    o.status,
    o.payment_status,
    o.payment_method,
    o.payment_plan,
    o.deposit_percent,
    o.required_initial_payment,
    o.amount_paid,
    o.balance_due,
    o.subtotal,
    o.discount_total,
    o.try_before_credit_total,
    o.shipping_total,
    o.total,
    o.shipping_method,
    o.carrier,
    o.tracking_code,
    o.created_at,
    o.confirmed_at,
    o.preparing_at,
    o.shipped_at,
    o.delivered_at,
    o.cancelled_at,
    o.payment_confirmed_at,
    o.refunded_at
  into v_order
  from public.orders o
  where upper(trim(coalesce(o.order_code, ''))) = v_code
    and (
      lower(trim(coalesce(o.customer_email, ''))) = lower(v_contact)
      or (
        length(v_contact_digits) >= 6
        and regexp_replace(coalesce(o.customer_phone, ''), '[^0-9]', '', 'g') = v_contact_digits
      )
    )
  order by o.id desc
  limit 1;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'display_name', coalesce(oi.display_name, 'Producto'),
        'item_type', coalesce(oi.item_type, 'product'),
        'product_id', oi.product_id,
        'quantity', coalesce(oi.quantity, 1),
        'ml', oi.ml,
        'unit_price', coalesce(oi.unit_price, 0),
        'total_price', coalesce(oi.total_price, 0),
        'review_status', (
          select pr.status
          from public.product_reviews pr
          where pr.order_id = v_order.id
            and pr.product_id = oi.product_id
          order by pr.id desc
          limit 1
        )
      )
      order by oi.id
    ),
    '[]'::jsonb
  )
  into v_items
  from public.order_items oi
  where oi.order_id = v_order.id;

  return jsonb_build_object(
    'ok', true,
    'order_code', v_order.order_code,
    'status', v_order.status,
    'payment_status', v_order.payment_status,
    'payment_method', v_order.payment_method,
    'payment_plan', v_order.payment_plan,
    'deposit_percent', v_order.deposit_percent,
    'required_initial_payment', v_order.required_initial_payment,
    'amount_paid', v_order.amount_paid,
    'balance_due', v_order.balance_due,
    'subtotal', v_order.subtotal,
    'discount_total', v_order.discount_total,
    'try_before_credit_total', v_order.try_before_credit_total,
    'shipping_total', v_order.shipping_total,
    'total', v_order.total,
    'shipping_method', v_order.shipping_method,
    'carrier', v_order.carrier,
    'tracking_code', v_order.tracking_code,
    'created_at', v_order.created_at,
    'confirmed_at', v_order.confirmed_at,
    'preparing_at', v_order.preparing_at,
    'shipped_at', v_order.shipped_at,
    'delivered_at', v_order.delivered_at,
    'cancelled_at', v_order.cancelled_at,
    'payment_confirmed_at', v_order.payment_confirmed_at,
    'refunded_at', v_order.refunded_at,
    'items', v_items
  );
end;
$$;

revoke all on function public.get_product_reviews_v2(bigint, integer, integer) from public;
revoke all on function public.submit_verified_product_review_v2(bigint, text, text, integer, text, text, text) from public;
revoke all on function public.admin_get_product_reviews_v2(text, text, integer, integer) from public;
revoke all on function public.admin_update_product_review_v2(bigint, text, boolean, text) from public;
revoke all on function public.get_public_order_status(text, text) from public;

grant execute on function public.get_product_reviews_v2(bigint, integer, integer) to anon, authenticated;
grant execute on function public.submit_verified_product_review_v2(bigint, text, text, integer, text, text, text) to anon, authenticated;
grant execute on function public.get_public_order_status(text, text) to anon, authenticated;
grant execute on function public.admin_get_product_reviews_v2(text, text, integer, integer) to authenticated;
grant execute on function public.admin_update_product_review_v2(bigint, text, boolean, text) to authenticated;

commit;
