-- AromaLParfum — PASO 61
-- Analytics First‑Party V2 — embudo real + atribución anónima + retención manual
-- Ejecutar UNA sola vez en Supabase > SQL Editor antes de subir el frontend del Paso 61.
--
-- PRIVACIDAD
-- - NO se guardan nombres, emails, teléfonos, direcciones, IPs ni texto libre.
-- - session_id llega como identificador aleatorio y se persiste únicamente como hash MD5.
-- - UTM/campaign/route se limitan a caracteres tipo slug.
-- - La facturación NUNCA sale de estos eventos: sale de public.orders verificados.

create table if not exists public.store_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_hash text not null,
  route text not null default 'home',
  route_key text not null default 'home',
  product_id bigint,
  campaign_slug text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer_host text,
  device_class text not null default 'desktop',
  cart_lines integer not null default 0,
  cart_quantity integer not null default 0,
  created_at timestamptz not null default now(),
  constraint store_analytics_event_name_chk check (
    event_name in (
      'session_start',
      'page_view',
      'product_view',
      'add_to_cart',
      'checkout_start',
      'checkout_submit',
      'order_created'
    )
  ),
  constraint store_analytics_device_chk check (device_class in ('mobile','tablet','desktop')),
  constraint store_analytics_cart_lines_chk check (cart_lines between 0 and 999),
  constraint store_analytics_cart_quantity_chk check (cart_quantity between 0 and 9999)
);

create index if not exists idx_store_analytics_created_at
  on public.store_analytics_events(created_at desc);

create index if not exists idx_store_analytics_event_created
  on public.store_analytics_events(event_name, created_at desc);

create index if not exists idx_store_analytics_session_created
  on public.store_analytics_events(session_hash, created_at desc);

create index if not exists idx_store_analytics_product_created
  on public.store_analytics_events(product_id, created_at desc)
  where product_id is not null;

create index if not exists idx_store_analytics_campaign_created
  on public.store_analytics_events(campaign_slug, created_at desc)
  where campaign_slug is not null and campaign_slug <> '';

alter table public.store_analytics_events enable row level security;
revoke all on table public.store_analytics_events from public, anon, authenticated;

-- Ingesta pública controlada. Un request acepta hasta 20 eventos.
create or replace function public.track_store_events_v2(
  p_events jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event jsonb;
  v_event_name text;
  v_session_id text;
  v_session_hash text;
  v_route text;
  v_route_key text;
  v_campaign text;
  v_utm_source text;
  v_utm_medium text;
  v_utm_campaign text;
  v_referrer_host text;
  v_device text;
  v_product_id bigint;
  v_cart_lines integer;
  v_cart_quantity integer;
  v_recent_count integer;
  v_inserted integer := 0;
  v_skipped integer := 0;
begin
  if p_events is null or jsonb_typeof(p_events) <> 'array' then
    return jsonb_build_object('ok', false, 'error', 'invalid_payload');
  end if;

  if jsonb_array_length(p_events) < 1 then
    return jsonb_build_object('ok', true, 'inserted', 0, 'skipped', 0);
  end if;

  if jsonb_array_length(p_events) > 20 then
    return jsonb_build_object('ok', false, 'error', 'too_many_events');
  end if;

  for v_event in select value from jsonb_array_elements(p_events)
  loop
    v_event_name := lower(trim(coalesce(v_event ->> 'event_name', '')));

    if v_event_name not in (
      'session_start',
      'page_view',
      'product_view',
      'add_to_cart',
      'checkout_start',
      'checkout_submit',
      'order_created'
    ) then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    -- Solo identificadores aleatorios simples. Nunca se guarda el valor crudo.
    v_session_id := left(
      regexp_replace(coalesce(v_event ->> 'session_id', ''), '[^A-Za-z0-9_-]', '', 'g'),
      100
    );

    if length(v_session_id) < 8 then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    v_session_hash := md5(v_session_id);

    -- Límite antiabuso por sesión: máximo 250 filas cada 10 minutos.
    select count(*)::integer
    into v_recent_count
    from public.store_analytics_events e
    where e.session_hash = v_session_hash
      and e.created_at >= now() - interval '10 minutes';

    if v_recent_count >= 250 then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    v_route := left(
      regexp_replace(lower(coalesce(v_event ->> 'route', 'home')), '[^a-z0-9_-]', '', 'g'),
      60
    );
    if v_route = '' then v_route := 'home'; end if;

    v_route_key := left(
      regexp_replace(lower(coalesce(v_event ->> 'route_key', v_route)), '[^a-z0-9:_-]', '', 'g'),
      180
    );
    if v_route_key = '' then v_route_key := v_route; end if;

    v_campaign := nullif(left(regexp_replace(lower(coalesce(v_event ->> 'campaign_slug', '')), '[^a-z0-9._~-]', '', 'g'), 120), '');
    v_utm_source := nullif(left(regexp_replace(lower(coalesce(v_event ->> 'utm_source', '')), '[^a-z0-9._~-]', '', 'g'), 120), '');
    v_utm_medium := nullif(left(regexp_replace(lower(coalesce(v_event ->> 'utm_medium', '')), '[^a-z0-9._~-]', '', 'g'), 120), '');
    v_utm_campaign := nullif(left(regexp_replace(lower(coalesce(v_event ->> 'utm_campaign', '')), '[^a-z0-9._~-]', '', 'g'), 120), '');
    v_referrer_host := nullif(left(regexp_replace(lower(coalesce(v_event ->> 'referrer_host', '')), '[^a-z0-9.-]', '', 'g'), 200), '');

    v_device := lower(coalesce(v_event ->> 'device_class', 'desktop'));
    if v_device not in ('mobile','tablet','desktop') then v_device := 'desktop'; end if;

    v_product_id := null;
    if coalesce(v_event ->> 'product_id', '') ~ '^[0-9]{1,18}$' then
      v_product_id := (v_event ->> 'product_id')::bigint;
      if v_product_id <= 0 then v_product_id := null; end if;
    end if;

    v_cart_lines := 0;
    if coalesce(v_event ->> 'cart_lines', '') ~ '^[0-9]{1,4}$' then
      v_cart_lines := least(999, greatest(0, (v_event ->> 'cart_lines')::integer));
    end if;

    v_cart_quantity := 0;
    if coalesce(v_event ->> 'cart_quantity', '') ~ '^[0-9]{1,5}$' then
      v_cart_quantity := least(9999, greatest(0, (v_event ->> 'cart_quantity')::integer));
    end if;

    insert into public.store_analytics_events (
      event_name,
      session_hash,
      route,
      route_key,
      product_id,
      campaign_slug,
      utm_source,
      utm_medium,
      utm_campaign,
      referrer_host,
      device_class,
      cart_lines,
      cart_quantity
    ) values (
      v_event_name,
      v_session_hash,
      v_route,
      v_route_key,
      v_product_id,
      v_campaign,
      v_utm_source,
      v_utm_medium,
      v_utm_campaign,
      v_referrer_host,
      v_device,
      v_cart_lines,
      v_cart_quantity
    );

    v_inserted := v_inserted + 1;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'inserted', v_inserted,
    'skipped', v_skipped
  );
end;
$$;

revoke all on function public.track_store_events_v2(jsonb) from public;
grant execute on function public.track_store_events_v2(jsonb) to anon, authenticated;

-- Dashboard Admin: devuelve solo agregados anónimos + pedidos pagados verificados.
create or replace function public.admin_get_conversion_analytics_v2(
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from timestamptz := coalesce(p_from, now() - interval '30 days');
  v_to timestamptz := coalesce(p_to, now());
  v_sessions bigint := 0;
  v_product_views bigint := 0;
  v_cart_adds bigint := 0;
  v_checkout_started bigint := 0;
  v_checkout_submitted bigint := 0;
  v_order_created bigint := 0;
  v_paid_orders bigint := 0;
  v_event_count bigint := 0;
  v_sources jsonb := '[]'::jsonb;
  v_devices jsonb := '[]'::jsonb;
  v_products jsonb := '[]'::jsonb;
  v_campaigns jsonb := '[]'::jsonb;
  v_daily jsonb := '[]'::jsonb;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'defanissantiago@gmail.com' then
    raise exception 'Solo administrador.';
  end if;

  if v_from >= v_to then
    raise exception 'Rango de fechas inválido.';
  end if;

  select
    count(*)::bigint,
    count(distinct session_hash) filter (where event_name in ('session_start','page_view'))::bigint,
    count(distinct session_hash) filter (where event_name = 'product_view')::bigint,
    count(distinct session_hash) filter (where event_name = 'add_to_cart')::bigint,
    count(distinct session_hash) filter (where event_name = 'checkout_start')::bigint,
    count(distinct session_hash) filter (where event_name = 'checkout_submit')::bigint,
    count(distinct session_hash) filter (where event_name = 'order_created')::bigint
  into
    v_event_count,
    v_sessions,
    v_product_views,
    v_cart_adds,
    v_checkout_started,
    v_checkout_submitted,
    v_order_created
  from public.store_analytics_events e
  where e.created_at >= v_from
    and e.created_at < v_to;

  select count(*)::bigint
  into v_paid_orders
  from public.orders o
  where o.payment_status = 'pagado'
    and o.created_at >= v_from
    and o.created_at < v_to;

  -- Una sola fila de adquisición por sesión: el primer session_start.
  with first_sessions as (
    select distinct on (e.session_hash)
      e.session_hash,
      coalesce(nullif(e.utm_source, ''), nullif(e.referrer_host, ''), 'direct') as source,
      coalesce(nullif(e.utm_medium, ''), case when nullif(e.referrer_host, '') is not null then 'referral' else 'none' end) as medium
    from public.store_analytics_events e
    where e.created_at >= v_from
      and e.created_at < v_to
      and e.event_name = 'session_start'
    order by e.session_hash, e.created_at asc, e.id asc
  ), grouped as (
    select source, medium, count(*)::bigint as sessions
    from first_sessions
    group by source, medium
  ), ranked as (
    select
      source,
      medium,
      sessions,
      case when sum(sessions) over () > 0
        then round((sessions::numeric / sum(sessions) over ()) * 100, 1)
        else 0 end as share_pct
    from grouped
    order by sessions desc, source
    limit 12
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'source', source,
    'medium', medium,
    'sessions', sessions,
    'share_pct', share_pct
  )), '[]'::jsonb)
  into v_sources
  from ranked;

  with first_devices as (
    select distinct on (e.session_hash)
      e.session_hash,
      e.device_class
    from public.store_analytics_events e
    where e.created_at >= v_from
      and e.created_at < v_to
      and e.event_name = 'session_start'
    order by e.session_hash, e.created_at asc, e.id asc
  ), grouped as (
    select device_class, count(*)::bigint as sessions
    from first_devices
    group by device_class
  ), ranked as (
    select
      device_class,
      sessions,
      case when sum(sessions) over () > 0
        then round((sessions::numeric / sum(sessions) over ()) * 100, 1)
        else 0 end as share_pct
    from grouped
    order by sessions desc, device_class
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'device_class', device_class,
    'sessions', sessions,
    'share_pct', share_pct
  )), '[]'::jsonb)
  into v_devices
  from ranked;

  with per_product as (
    select
      e.product_id,
      count(distinct e.session_hash) filter (where e.event_name = 'product_view')::bigint as view_sessions,
      count(distinct e.session_hash) filter (where e.event_name = 'add_to_cart')::bigint as cart_sessions
    from public.store_analytics_events e
    where e.created_at >= v_from
      and e.created_at < v_to
      and e.product_id is not null
      and e.event_name in ('product_view','add_to_cart')
    group by e.product_id
  ), ranked as (
    select
      pp.product_id,
      coalesce(p.nombre, 'Producto #' || pp.product_id::text) as name,
      coalesce(p.marca, '') as brand,
      pp.view_sessions,
      pp.cart_sessions,
      case when pp.view_sessions > 0
        then round((pp.cart_sessions::numeric / pp.view_sessions) * 100, 1)
        else 0 end as view_to_cart_rate
    from per_product pp
    left join public.products p on p.id = pp.product_id
    where pp.view_sessions > 0
    order by pp.view_sessions desc, pp.cart_sessions desc, pp.product_id
    limit 15
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', product_id,
    'name', name,
    'brand', brand,
    'view_sessions', view_sessions,
    'cart_sessions', cart_sessions,
    'view_to_cart_rate', view_to_cart_rate
  )), '[]'::jsonb)
  into v_products
  from ranked;

  with grouped as (
    select
      e.campaign_slug,
      count(distinct e.session_hash)::bigint as sessions,
      count(distinct e.session_hash) filter (where e.event_name = 'product_view')::bigint as product_view_sessions,
      count(distinct e.session_hash) filter (where e.event_name = 'add_to_cart')::bigint as cart_sessions,
      count(distinct e.session_hash) filter (where e.event_name = 'checkout_start')::bigint as checkout_sessions
    from public.store_analytics_events e
    where e.created_at >= v_from
      and e.created_at < v_to
      and coalesce(e.campaign_slug, '') <> ''
    group by e.campaign_slug
    order by sessions desc, e.campaign_slug
    limit 15
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'campaign_slug', campaign_slug,
    'sessions', sessions,
    'product_view_sessions', product_view_sessions,
    'cart_sessions', cart_sessions,
    'checkout_sessions', checkout_sessions
  )), '[]'::jsonb)
  into v_campaigns
  from grouped;

  with grouped as (
    select
      (e.created_at at time zone 'America/Argentina/Buenos_Aires')::date as day,
      count(distinct e.session_hash)::bigint as sessions
    from public.store_analytics_events e
    where e.created_at >= v_from
      and e.created_at < v_to
      and e.event_name = 'session_start'
    group by 1
    order by 1
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'day', day,
    'sessions', sessions
  )), '[]'::jsonb)
  into v_daily
  from grouped;

  return jsonb_build_object(
    'from', v_from,
    'to', v_to,
    'event_count', v_event_count,
    'funnel', jsonb_build_object(
      'visits', v_sessions,
      'sessions', v_sessions,
      'product_views', v_product_views,
      'cart_adds', v_cart_adds,
      'checkout_started', v_checkout_started,
      'checkout_submitted', v_checkout_submitted,
      'order_created', v_order_created,
      'verified_paid_orders', v_paid_orders,
      'product_to_cart_rate', case when v_product_views > 0 then round((v_cart_adds::numeric / v_product_views) * 100, 1) else 0 end,
      'cart_to_checkout_rate', case when v_cart_adds > 0 then round((v_checkout_started::numeric / v_cart_adds) * 100, 1) else 0 end,
      'session_to_paid_rate', case when v_sessions > 0 then round((v_paid_orders::numeric / v_sessions) * 100, 1) else 0 end
    ),
    'sources', v_sources,
    'devices', v_devices,
    'top_products', v_products,
    'campaigns', v_campaigns,
    'daily', v_daily
  );
end;
$$;

revoke all on function public.admin_get_conversion_analytics_v2(timestamptz, timestamptz) from public;
grant execute on function public.admin_get_conversion_analytics_v2(timestamptz, timestamptz) to authenticated;

-- Limpieza manual para mantener bajo el crecimiento de la tabla en el plan gratuito.
create or replace function public.admin_purge_analytics_v2(
  p_keep_days integer default 180
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_keep_days integer := least(730, greatest(30, coalesce(p_keep_days, 180)));
  v_deleted bigint := 0;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'defanissantiago@gmail.com' then
    raise exception 'Solo administrador.';
  end if;

  delete from public.store_analytics_events
  where created_at < now() - make_interval(days => v_keep_days);

  get diagnostics v_deleted = row_count;

  return jsonb_build_object(
    'ok', true,
    'keep_days', v_keep_days,
    'deleted', v_deleted
  );
end;
$$;

revoke all on function public.admin_purge_analytics_v2(integer) from public;
grant execute on function public.admin_purge_analytics_v2(integer) to authenticated;

-- Comprobación informativa al final del script.
select jsonb_build_object(
  'paso', 61,
  'table', 'store_analytics_events',
  'public_insert', 'solo_rpc_controlada',
  'direct_table_access', 'revocado',
  'pii', 'no_guardada',
  'retention_cleanup', 'admin_purge_analytics_v2'
) as paso61_setup;
